### ISSUE TITLE
odt2dw - ODT file upload not possible

### ISSUE THREAD

**Issue by kredn** [garlik-gag/dokuwiki-plugin-odt2dw#11]
Hi,
I hope I could say this is a great plugin, but I can't because I was not able to test it.
I have installed Dokuwiki on existing Apache server. It runs fine as far as I could see until now.
Then I have installed odt2dw plugin. I changed nothing particular in odt2dw config.
When I try to upload an ODT file to some page I get:

odt2dw : er_odtFile_upload : Something went wrong with the file's upload : 1
odt2dw : er_checkUploadResult : Something is wrong with the uploaded file

Has anyone seen this before?
Any hint would be great.

**Comment by garlik-gag** [comment]
Hi kredn,

the message return the error code. it is the '1' finish the first line.

The error code 1 meant :
UPLOAD_ERR_INI_SIZE
    Value: 1; The uploaded file exceeds the upload_max_filesize directive in php.ini.

So your odt file is to big. You need to update your php.ini file to allow larger file.

You should see http://php.net/manual/en/features.file-upload.errors.php for more info.
