### ISSUE TITLE
odt upload failed, log entries not helping

### ISSUE THREAD

**Issue by PifPof73** [garlik-gag/dokuwiki-plugin-odt2dw#30]
Hi,
if I try to upload an odt file, I get this error messages (both inside wiki and inside the log file):
2018-04-27T16:10:27+02:00:cweidmann:er_odtFile_upload : Allgemeiner Fehler beim Datei-Upload : 1
2018-04-27T16:10:27+02:00:cweidmann:er_checkUploadResult : Allgemeiner Fehler bei der hochgeladenen Datei
2018-04-27T16:10:27+02:00:cweidmann:er_pg_dir : Kann das temporäre Arbeitsverzeichnis nicht entfernen : /

In the config file the tmp - path is inside the dokuwiki/data/tmp path with owning of the apache2 user.

System:
- Ubuntu 16.04.4 LTS, Kernel 4.4.0-112-generic
- PHP 7.0.28-0ubuntu0.16.04.1 with extensions zip, xml, xsl
- Apache/2.4.18 (Ubuntu)
- Dokuwiki Release 2018-04-22 "Greebo"

Do you have any hint what could go wrong?
It worked some longer version ago, but was not tested on every update.
Thx in advance,
Greetings
PifPof

**Comment by tryfail** [comment]
> if I try to upload an odt file, I get this error messages (both inside wiki and inside the log file):
> 2018-04-27T16:10:27+02:00:cweidmann:er_odtFile_upload : Allgemeiner Fehler beim Datei-Upload : 1
> 2018-04-27T16:10:27+02:00:cweidmann:er_checkUploadResult : Allgemeiner Fehler bei der hochgeladenen Datei
> 2018-04-27T16:10:27+02:00:cweidmann:er_pg_dir : Kann das temporäre Arbeitsverzeichnis nicht entfernen : /

Have you seen the closed issue #11 at https://github.com/garlik-gag/dokuwiki-plugin-odt2dw/issues/11

I have not replicated this issue and proposed solution.
