### ISSUE TITLE
Images will are not uploaded

### ISSUE THREAD

**Issue by stvoigt** [garlik-gag/dokuwiki-plugin-odt2dw#9]
This Plugin is fantastic! Thanks a lot for this work. ODT-file is uploaded and the content is displayed as it should be. But there is one thing that does not work with me in different systems (I have tried Debian as well as IIS7). Images are not uploaded, that means links to images are there, but no files (see Screenshot1). 
![screenshot1](https://f.cloud.github.com/assets/2620833/1191336/f6ba33dc-244e-11e3-8325-aae88addcb75.PNG)

I've created my ODT-file with MS Word 2010. If I open the ODT with ZIP, I can see the images inside the folder "media". I get only a positive "error message" (odt2dw : ok_unzip : Extraction correctly processing : content.xml).

**Comment by algorys** [comment]
I've the same issue, with Dokuwiki Hrun (Release 2014-09-29), I've to save with another editor text (like open office) before download my document inside the wiki. 

Does your project still alive ?

Do you think you'll make next release of your plugin ?

Otherwise, it's work very well.

Thanks for help.

**Comment by garlik-gag** [comment]
Hi,
I try to solv this issues on branch bug10.
https://github.com/garlik-gag/dokuwiki-plugin-odt2dw/tree/bug10

I remove the hard coded "Picture" directory and keep the path on the document.

Tell me if it work.

Cheer,
Garlik

**Comment by garlik-gag** [comment]
Damn, it's bug #9 :)
But it is solv in the branch bug10.

**Comment by stvoigt** [comment]
Hi,
thanks for working on this bug. But it did not change anything for me. I am working with 2015-08-10a "Detritus" and have installed https://github.com/garlik-gag/dokuwiki-plugin-odt2dw/archive/bug10.zip (which should be the correct one). I've turned on all messages, but did not get any error or warning.  
I have uploaded my ODT-Testdocument (made with MS Word 2010) to my public dropbox, if you want to test your code against it: https://www.dropbox.com/s/vn510qbii1z1y9b/testdocument_odtimport.odt?dl=0
Hope this can help... 
Best wishes
Stefan

**Comment by garlik-gag** [comment]
Hi,
thanks for the test file.

It help me show what goes wrong.
2 differents things. The regexp and the hardcoded Picture directory.

I update the bug10 branch and test it. It works with your odt test document.

Could you try it with a real file ?

**Comment by stvoigt** [comment]
Hi, 
I've tested this branch with another MS Word produced ODT-File. It worked without any error/warning. Great! Thanks a lot!
